version: "3"
services:
  web:
    image: companies-twitter
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    volumes:
      - companies_twitter_node_modules:/app/node_modules
    container_name: companies-twitter-container
    tty: true
volumes:
  companies_twitter_node_modules:
